server:
  port: 8080

spring:
  application:
    name: lecture-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:/localhost:3306/lecture_enrollment?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: '@Hong34040'

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate # Entity? ???? ?? ?? ???? ??
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true # true ??? JPA ??? ?? ??
    database: mysql
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        format_sql: true # JPA? ???? Hibernate? ????? ??? SQL? ???? ????.
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug